#!/usr/bin/env bash
# Pins the web-endpoint SkillPack's sidecar image to the installed chart version.
#
# WHY THIS EXISTS
# ---------------
# The chart ships web-endpoint with `sidecar.image: .../web-proxy:latest`. That
# tag is mutable and tracks the newest release, while the control plane is
# pinned. Run a 0.10.38 control plane for long enough and `:latest` silently
# becomes a much newer web-proxy — which then crash-loops with exit code 2 and
# ZERO log output, roughly every 30s, forever. Nothing in the events or logs
# points at version skew; the pods just never bind :8080 and both liveness and
# readiness report connection refused.
#
# Observed on this cluster: ~5,680 restarts across both agents' serving
# Deployments before the cause was identified.
#
# Pinning the sidecar to the control plane's own version removes the drift.
#
# Two things are needed, not one:
#   1. patch the SkillPack (what NEW Deployments will use), and
#   2. purge the cached :latest image from the Kind node — pullPolicy is
#      IfNotPresent, so a stale cached layer would otherwise be reused.
# The serving Deployments are generated by the AgentRun controller from the
# SkillPack, so deleting the serving AgentRuns makes it regenerate them with the
# pinned image (a rollout restart alone would keep :latest in the pod spec).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NS="${SYMPOZIUM_NAMESPACE:-sympozium-system}"
KCTX="${KUBE_CONTEXT:-kind-cluster2}"
K="kubectl --context ${KCTX}"

VER="${SYMPOZIUM_CHART_VERSION:-}"
if [[ -z "$VER" ]]; then
    VER="$(helm list -n "$NS" -f '^sympozium$' -o json 2>/dev/null \
           | sed -n 's/.*"chart":"sympozium-\([^"]*\)".*/\1/p')"
fi
[[ -n "$VER" ]] || { echo "ERROR: could not determine the installed chart version." >&2; exit 1; }

IMAGE="ghcr.io/sympozium-ai/sympozium/web-proxy:v${VER}"
echo "==> Pinning web-endpoint sidecar to ${IMAGE}"

CURRENT="$($K get skillpack web-endpoint -n "$NS" -o jsonpath='{.spec.sidecar.image}' 2>/dev/null || true)"
[[ -n "$CURRENT" ]] || { echo "ERROR: web-endpoint SkillPack not found in $NS." >&2; exit 1; }
echo "    current: ${CURRENT}"

if [[ "$CURRENT" == "$IMAGE" ]]; then
    echo "    already pinned, nothing to do."
    exit 0
fi

$K patch skillpack web-endpoint -n "$NS" --type=merge \
    -p "{\"spec\":{\"sidecar\":{\"image\":\"${IMAGE}\"}}}"

# Drop the stale mutable tag from the node's image cache (IfNotPresent).
if command -v docker &>/dev/null; then
    NODE="${KIND_NODE:-cluster2-control-plane}"
    if docker ps --format '{{.Names}}' | grep -qx "$NODE"; then
        echo "==> Purging cached :latest from ${NODE}"
        docker exec "$NODE" crictl rmi ghcr.io/sympozium-ai/sympozium/web-proxy:latest 2>/dev/null \
            || echo "    (not cached, nothing to purge)"
    fi
fi

# Regenerate the serving Deployments from the updated SkillPack.
echo "==> Recreating serving AgentRuns so the controller applies the new image"
for run in $($K get agentruns -n "$NS" -o name 2>/dev/null | grep -E 'web-endpoint$' || true); do
    echo "    deleting ${run}"
    $K delete "$run" -n "$NS" --ignore-not-found >/dev/null
done

echo "==> Waiting for serving Deployments to come back…"
sleep 5
for d in $($K get deploy -n "$NS" -o name 2>/dev/null | grep -E 'web-endpoint-server$' || true); do
    $K rollout status "$d" -n "$NS" --timeout=180s || echo "    WARNING: $d not ready"
done

echo ""
echo "Done. Serving Deployments now run ${IMAGE}."
echo "NOTE: the AgentRun controller also recreates the Services as ClusterIP."
echo "Re-run ./sympozium-lb-setup.sh to restore their MetalLB addresses."
